### ISSUE TITLE
Error fetching entities from Home Assistant

### ISSUE THREAD

**Issue by Pandabeer40** [apop880/photodash#30]
I receive the following when trying to make a new configuration:

Error fetching entities from Home Assistant

I try it with a long-lived token and without  - what can be the problem?
![Schermafbeelding 2023-03-05 200947](https://user-images.githubusercontent.com/44602201/222980715-4fdfff93-ce70-4d72-81d2-a4edb0fa14bc.jpg)

**Comment by apop880** [comment]
@Pandabeer40 Did you complete the step of adding your Photodash URL to the CORS allowed origins in Home Assistant? (step 4 at https://photodash.apop.tech/docs/installation)

**Comment by Pandabeer40** [comment]
Hi Alex,

Yes I've added this to the configuration.yaml - now overnight - it look's like it works - now I'm going to try to add Google Photos (local is working now - thanks)

**Comment by apop880** [comment]
Glad to hear it! The next major release will add a link to the docs in that error message, so that hopefully nobody else is tripped up by the same issue.
